### ISSUE TITLE
Negative values?

### ISSUE THREAD

**Issue by ekandreas** [AnourValar/office#1]
How could I accomplish a negative value from the code given?
Excel doesnt allow the syntax [data.prop] for that.

Just a negative number is an example. I want to use formulas in general.

**Comment by ekandreas** [comment]
And thanks for a great package.

**Comment by AnourValar** [comment]
Thanks for your feedback!

I'm not quite understand your issue. Could give some example with data please?

**Comment by ekandreas** [comment]
Place a code in a template. 
Format the code so that it will be a negative value. 
Or place a code in a template and fotmat it så that it will be rounded. 
Or any other Excel function in combination with template codes.

**Comment by AnourValar** [comment]
Excel allows to paste a value with a broken formula to the cell. Just try copy-paste on cell.

Another solution is keeping the whole formula in params.

**Comment by ekandreas** [comment]
Ok, thanks!
