### ISSUE TITLE
Exported XLSX file showing a loading time error 

### ISSUE THREAD

**Issue by eldhojoypappara** [AnourValar/office#10]
![image](https://user-images.githubusercontent.com/37293887/195375050-73294d60-5c95-40ef-9b76-457f5d56d72e.png)

Once open the exported file showing this error on loading

using code for reference:

(new \AnourValar\Office\SheetsService())
        ->generate(
            'existing_document.xlsx', // path to template
            $data,
            false // input data
        )
        ->saveAs(
            'generated_document.xlsx', // path to save
            \AnourValar\Office\Format::Xlsx // save format
        );

**Comment by AnourValar** [comment]
Hello!

I need some samples to reproduce this bug.
Have you tried to save it as PDF?

**Comment by eldhojoypappara** [comment]
HI
I have attached the sample files and sample data for creating the file here please check and help me with a solution
$data = [
    'user' => [
        [
            'cmc' => 'BlackLion Law t/a ClaimLion Law',
            'date' => '20-10-2022',
            'sp_no' => 'Submission 1',
            'claim_ref' => 'j29W9vSLAl',
            'fname' => 'sethu',
            'sur_name' => 'ram',
        ],
        [
            'cmc' => 'BlackLion Law t/a ClaimLion Law',
            'date' => '20-10-2022',
            'sp_no' => 'Submission 1',
            'claim_ref' => 'g7hWCk7uHM',
            'fname' => 'test',
            'sur_name' => 'llead',
        ]
    ]
];
[existing_document.xlsx](https://github.com/AnourValar/office/files/9832895/existing_document.xlsx)
[generated_document.xlsx](https://github.com/AnourValar/office/files/9832897/generated_document.xlsx)

**Comment by AnourValar** [comment]
Hello!

The template (existing_document.xlsx) has a huge range of columns (A1:AMK1).
Here is the fixed template: [existing_document.xlsx](https://github.com/AnourValar/office/files/9892911/existing_document.xlsx)
