### ISSUE TITLE
Q: performance optimizations?

### ISSUE THREAD

**Issue by ekandreas** [AnourValar/office#11]
Hi!
Any plans on making some performance optimizations in Parser.php? When we run our datasheets it takes around 30-300 seconds to traverse the data. Very slow loops inside Parser.php with multiple for-loops inside for-loops.

It feels like the package parhaps need some caching and loop optimizations.

Functions very slow are calculateDataSchema and replaceMarkers.

Package version 2.1.2.

**Comment by ekandreas** [comment]
How can we help you get insight in this issue?

**Comment by AnourValar** [comment]
Hello!

I'm honest curious, why do you need to place so big data on the template? If you're just need to export the grid - there are better ways to do that.

My personal cases to use this package - replacing 10-100 cells with the values in a business specific document (template).

I have some plans to rewrite the whole Parser to add more features. I need some time to think :)

**Comment by ekandreas** [comment]
It's not that big. Just 70 cols and 250 rows. But if you measure how many times the inner loop is executed there is a count by 800 miljon. 
Tripple foreach and array_keys inside makes our transaction around 300s. That is slow for us 😊

**Comment by AnourValar** [comment]
I have made some optimization for the Parser. I hope I've helped.

**Comment by ekandreas** [comment]
It made a change but now it is even slower.

**Comment by AnourValar** [comment]
@ekandreas , I have released some new optimization... At least I hope I did not make even worse (:
