### ISSUE TITLE
Conditional formatting rules not propagating in 1 dimensional table row spreadsheet

### ISSUE THREAD

**Issue by computerchemist** [AnourValar/office#13]
I have set up a 1-dimensional table row similar to the "products" example in template1 spreadsheet.

One of the cells in the template of the 1-dimensional table row has conditional formatting set, so that depending upon the value of the cell it will change colour style.

This works correctly for the first row returned but does not appear to propagate to any other rows, however the text formatting is correctly propagated to all rows.

I can see using LibreOffice or Excel that the conditional formatting is simply not there on any row following the first.

**Comment by AnourValar** [comment]
Fixed in 2.2.0.

Thanks for a feedback ;)
