### ISSUE TITLE
multidimensional array output

### ISSUE THREAD

**Issue by Electrica** [AnourValar/office#14]
Good afternoon. How can I display when there is another array in the array?

![image](https://user-images.githubusercontent.com/3878386/203034865-670a3df6-5518-40e0-9c01-5ff24d27ca43.png)

![image](https://user-images.githubusercontent.com/3878386/203035091-92ec25a1-1037-4229-9c91-dfe900fa837e.png)

**Comment by AnourValar** [comment]
There is no simple way to do that.
There are two "workaround" ways:

1. Concat "2 level" data into one variable per row.
2. Generate table dynamically. [Here ](https://github.com/AnourValar/office#dynamic-templates) is some example.
