### ISSUE TITLE
Invalid cell coordinate B7 H6 v.2.2.4

### ISSUE THREAD

**Issue by SDJeff** [AnourValar/office#15]
I have an empty XLS where i copied your example for products.

![CleanShot 2022-11-22 at 16 37 25](https://user-images.githubusercontent.com/2220942/203356268-fb50e392-9d07-4e7c-b4fa-5e1b11038c5a.png)

I dropped all other data placeholder out but the error remains.

every run the same error 'Invalid cell coordinate B7 H6'

If i bring only scalar values and not the array with the table it runs without error.

Is that already known?

**Comment by AnourValar** [comment]
Hello!

Could you provide the entire code and the xlsx template?

**Comment by SDJeff** [comment]
```
$calculation = Calculation::findOrFail($calc_id);

        $data = [
            // scalar
            'customer' => $calculation->address->address_line_1,
            'project' => $calculation->project->short_name,
            'agency_fee' => $calculation->agency_fee,
            'commission' => $calculation->discount_global,
            'agent' => $calculation->official_logistics_provider,
            'creator' => $calculation->creator->name,

            // one-dimensional table
            'products' => [],
        ];

        foreach ($calculation->positions as $item) {
            $data['products'][] = [
                'name' => $item->name,
                'price_base' => $item->price_base,
                'price_incl_surcharge' => $item->price_incl_surcharge,
                'quantity' => $item->quantity,
            ];
        }

        ray('Data for Spreadsheet: ', $data);

        //-------------------------
        // \AnourValar\Office
        //-------------------------
        // Save as XLSX (Excel)
        (new SheetsService())
            ->generate(
                storage_path('app/templates/Kalkulationsvorlage.xlsx'), // path to template
                $data, // input data
            )
            ->saveAs(
                storage_path('app/generated_document.xlsx'), // path to save
                Format::Xlsx, // save format
            );
    }
```

[Kalkulationsvorlage.bak.xlsx](https://github.com/AnourValar/office/files/10123991/Kalkulationsvorlage.bak.xlsx)
[Kalkulationsvorlage.xlsx](https://github.com/AnourValar/office/files/10123992/Kalkulationsvorlage.xlsx)

**Comment by AnourValar** [comment]
It is an issue with your template or a bug in Phpspreadsheet itself (insertNewRowBefore() is not working on your template).

Simplest solution - create a new excel file and paste the values.

**Comment by SDJeff** [comment]
Ok. Created empty file and started vom scratch again.
It works now. Did composer update before. One of this doings fixed it.
Thx.
