### ISSUE TITLE
Use \n to cell

### ISSUE THREAD

**Issue by Electrica** [AnourValar/office#19]
How can I use this construction so that line breaks work for me:

Write a newline character "\n" in a cell (ALT+"Enter")
In Microsoft Office Excel you get a line break in a cell by hitting ALT+"Enter". When you do that, it automatically turns on "wrap text" for the cell.

Here is how to achieve this in PhpSpreadsheet:

$spreadsheet->getActiveSheet()->getCell('A1')->setValue("hello\nworld");
$spreadsheet->getActiveSheet()->getStyle('A1')->getAlignment()->setWrapText(true);

**Comment by AnourValar** [comment]
Just enable the wrap text for necessary cells in your XLSX template via Excel
