### ISSUE TITLE
Multiple tabs?

### ISSUE THREAD

**Issue by ekandreas** [AnourValar/office#2]
We are trying to fill multiple tabs in Excel with data.
How do we accomplish multiple Excel tabs with data conversions?

Right now the component just takes the first sheet and not the other...

**Comment by AnourValar** [comment]
At this moment package only works with an active sheet (active tab in Excel).

I have plans to add multitab support in a future.

**Comment by AnourValar** [comment]
I have released the major update (2.x.x) which includes multi tabs support.
