### ISSUE TITLE
Value are set on wrong rows

### ISSUE THREAD

**Issue by papipsycho** [AnourValar/office#21]
Hello 

i discover a bug , when i mixed data repated and non repeated on 2 different lines, example here

![Capture d’écran 2023-03-22 192123](https://user-images.githubusercontent.com/20132010/226903781-d2195eed-9be3-421f-8018-b40cb4f43253.png)

if i my first line i put the columns [course.11.full_name], [course.13.full_name], [course.10.full_name] and [course.12.full_name],
and the line below  repeated dynamic data such like : [user.cohort.courses.11.progress], this data will be display but on the wrong row, it will be display on the row -1

Best

**Comment by AnourValar** [comment]
Hello!

Package doesn't support such cases. You can only place one array index per row.
