### ISSUE TITLE
Undefined method 'insertImage'

### ISSUE THREAD

**Issue by edgzxdev** [AnourValar/office#22]
I tried to insert an image with the name [map], but I get the error that insertImage method of SheetsInterface is not defined.
![image](https://user-images.githubusercontent.com/122640934/232067019-ef7932e6-07d7-4c94-add5-830847154935.png)

```
'bar' => function (\AnourValar\Office\Drivers\SheetsInterface $driver, $cell) {
                $driver->insertImage('test.png', $cell, ['width' => 100, 'offset_y' => -45]);
                return 'Logo!'; // replace marker "[bar]" with return value
            }
```

**Comment by AnourValar** [comment]
Method "insertImage" is not part of the interface... but the default driver (implementation) has this method. Your IDE can't see it.
