### ISSUE TITLE
How to fill cell with "[key_name]”

### ISSUE THREAD

**Issue by damian-2A** [AnourValar/office#24]
Hello,

Il looking for creating a double step excel filling and i need to fill some cell with the viariable appelation : "[key_name]";

How can i do that ?

Many thank for this plugin that is easy to use ! :)

**Comment by AnourValar** [comment]
Hi! You can you **hookBefore** method.

```
$data = [...];

(new \AnourValar\Office\SheetsService())
    ->hookBefore(function ($driver, array &$data) {
            $driver->setValue("A1", "[foo]");
    })
    ->generate('template.xlsx', $data)
    ->saveAs('generated_document.xlsx');
```
