### ISSUE TITLE
maennchen/zipstream-php ^3.1

### ISSUE THREAD

**Issue by n3storm** [AnourValar/office#26]
Library requires maennchen/zipstream-php 2.4.0 wich requires psr/http-message ^1.0 but spatie/laravel-medialibrary requires psr/http-message ^2.0|^3.0

I have installed maennchen/zipstream-php ^3.1 so no need to downgrade spatie/laravel-medialibrary

I am going to do some tests and report back to this issue if anouvlar/office is ok with zipstream upgrade.

**Comment by n3storm** [comment]
Everything works ok

**Comment by AnourValar** [comment]
Added support in [v2.5.0](https://github.com/AnourValar/office/releases/tag/2.5.0)
