### ISSUE TITLE
Support of Loop in Word Document and Custom Macro Tag support

### ISSUE THREAD

**Issue by mrgodhani** [AnourValar/office#27]
Hi there,

Out of curiosity, Does generating document from Word template supports Loops?

Also is it possible to customize macros so instead of having [foo] if we can customize it support our own like %foo% etc or any kind? reference: https://phpoffice.github.io/PHPWord/usage/template.html#setmacrochars

**Comment by AnourValar** [comment]
Hello

> Does generating document from Word template supports Loops?
No, it does not. This package are not using PHPWord either. PHPWord were useless in a time when a implemented Word templates (I don't know about now).

> Also is it possible to customize macros so instead of having [foo] if we can customize it support our own like %foo%
Nope. I'm afraid it is hardcoded ¯\(°_o)/¯
