### ISSUE TITLE
setRowHeight fit  based on content length 

### ISSUE THREAD

**Issue by quanhavn** [AnourValar/office#28]
I have an Excel file wit long text. 
I want to set the row height to auto fit based on the content.

Is there a way to do this? 

Thank you!

**Comment by quanhavn** [comment]
@AnourValar  can u help me? Please 🙇

**Comment by AnourValar** [comment]
This package does not work with Excel directly. It's using [Phpspreadsheet package](https://github.com/PHPOffice/PhpSpreadsheet) under the hood.

So, try [the official doc](https://phpspreadsheet.readthedocs.io/en/latest/search.html?q=height)
