### ISSUE TITLE
Problem with grouping

### ISSUE THREAD

**Issue by develgold** [AnourValar/office#4]
How to group data? I have tried with the following data:

```php
$data = [
    'categories' => [
        [
            'name' => 'Category 1',
            'products' => [
                [
                    'name' => 'Product 1',
                    'quantity' => 1,
                ],
                [
                    'name' => 'Product 2',
                    'quantity' => 2,
                ],
            ]
        ],
        [
            'name' => 'Category 2',
            'products' => [
                [
                    'name' => 'Product 3',
                    'quantity' => 3,
                ],
                [
                    'name' => 'Product 4',
                    'quantity' => 4,
                ],
            ]
        ],
    ]
];
```

![изображение](https://user-images.githubusercontent.com/27425101/176991527-afd80836-2986-4675-bd3d-e2cda62d3afe.png)

Result:

![изображение](https://user-images.githubusercontent.com/27425101/176991544-bea03b4e-4a23-4625-9482-d29b6165850d.png)

Or I misunderstand something?

**Comment by AnourValar** [comment]
Unfortunately this package does not support groups directly.

As work around - you could edit the template dynamically.
[Here](https://github.com/AnourValar/office#dynamic-templates) is an example.
