### ISSUE TITLE
Merged cell

### ISSUE THREAD

**Issue by develgold** [AnourValar/office#5]
Template:
![изображение](https://user-images.githubusercontent.com/27425101/177983172-54d21eea-5bda-40fc-8545-af56269ff053.png)

Params:
```php
$data = [
    'items' => [ [ 'item 1', 'item 2', 'item 3'  ] ]
];
```

Result:
![изображение](https://user-images.githubusercontent.com/27425101/177983111-e689bb0a-d443-42fd-912c-c45328a56c0f.png)

**Comment by AnourValar** [comment]
Hi there!
Multi rows ("vertical") merging is not implemented yet as well.

It is only works that way:
![image](https://user-images.githubusercontent.com/54237693/177986939-309a2b02-adda-413d-b783-3311b78a9533.png)
![image](https://user-images.githubusercontent.com/54237693/177986962-2c7f2292-e8dc-4e01-a802-91ccd1ae41ed.png)

Of course, you can always apply some changes via [hookAfter](https://github.com/AnourValar/office#advanced-usage)
