### ISSUE TITLE
out of memory - templates with (bad?) formulas

### ISSUE THREAD

**Issue by computerchemist** [AnourValar/office#7]
I have several excel documents that have formulas within that will give an out of memory error - if I copy and paste just the values into a new spreadsheet the test script works.
I believe the answer having googled this would be to allow granular control over setPreCalculateFormulas within the SheetsService function but I don't know where to add that in - is it possible to expose this as an attribute? Setting it to false would stop the OOM in these cases without reworking the sheet.

**Comment by computerchemist** [comment]
Thanks - just what I was looking for. This is an excellent tool!

**Comment by computerchemist** [comment]
I added in the hookBefore but it's throwing an error - have I got the syntax wrong?

```
(new \AnourValar\Office\SheetsService())
    ->hookBefore(
        function ($driver, array &$data) { $driver->spreadsheet->setPreCalculateFormulas(false); }
    )
    ->generate(
        'TEMPLATE.xlsx', // path to template
        $data // input data
    )
    ->saveAs(
        'generated_document.xlsx', // path to save
        \AnourValar\Office\Format::Xlsx // save format
    );
```

I am getting the following error:
```
PHP Fatal error:  Uncaught Error: Call to undefined method PhpOffice\PhpSpreadsheet\Spreadsheet::setPreCalculateFormulas() in test.php:71

```
Before I added in the hookBefore, the test program worked correctly, so I assume my base installation is good.

**Comment by AnourValar** [comment]
Sorry... I gave you a wrong example.
**setPreCalculateFormulas** is a method of writer and not of the phpspreadsheet itself.

So, you need the **hookSave** to replace the default driver behaviour:
`
(new \AnourValar\Office\SheetsService())
    ->generate('TEMPLATE.xlsx', $data)
    ->hookSave(function ($driver, $format) {
        $writer = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($driver->spreadsheet, 'Xlsx');
        $writer->setPreCalculateFormulas(false);
        $writer->save('php://output');
    })
    ->saveAs('generated_document.xlsx');
`
