### ISSUE TITLE
is this possible output convert in other format

### ISSUE THREAD

**Issue by dodhiyaimran** [AnourValar/office#8]
Hello Paul Redmond,

1) I want to input (template) docx format and output (saveAs) pdf format,  if is this possible  then please share sample code.

2) Mixer can support same first point (Ex. i have generate multiple docx from template and want to output(saveAs) a single pdf file) (Currently giving me Unhandled match case of type AnourValar\Office\Format error)

**Comment by AnourValar** [comment]
Hello!

DocumentService currenlty only supports DOCX.

Mixer and advanced features for Excel depends on Phpspreadsheet package. There are similar package for the .doc (PHPWord)... but it's just a beta with tons of bugs.
