### ISSUE TITLE
Q: possible to replace and not fill?

### ISSUE THREAD

**Issue by ekandreas** [AnourValar/office#9]
When using one-dimensional table I want the data filled not to expand the area.
We have calculations for the fields at the right position on a sheet that uses the filled table. The formulas will be affected/touched when filling data with this package. We want the calculations to be untouched.
Is it possible?

**Comment by AnourValar** [comment]
Hello!

I have plans to implement this feature in the future.
As for now... are you sure that added rows breaks the formulas?
